parameters:
  env(TOKEN): ''
  env(BUCKET_NAME): ''
  github_token: '%env(TOKEN)%'
  bucket_name: '%env(BUCKET_NAME)%'
  module_list_repository: 'prestashop/native-modules'
  prestashop_min_version: '1.7.8.7' # @toDo: update to 8.0.0 when released