imports:
  - { resource: parameters.yaml }

services:
  _defaults:
    public: true
    autowire: true

  Github\Client:
    calls:
      - authenticate: ['%github_token%', 'access_token_header']

  GuzzleHttp\Client:

  Psssst\ModuleParser:

  App\Util\ModuleUtils:

  App\Util\PrestaShopUtils:

  App\Command\GenerateJsonCommand:
    tags: ['console.command']

  App\Command\DownloadNativeModuleMainClasses:
    tags: ['console.command']

  App\Command\DownloadPrestaShopInstallVersions:
    tags: ['console.command']

  App\Command\CleanCommand:
    tags: ['console.command']

  App\Command\CheckReposCommand:
    tags: [ 'console.command' ]
