name: PRODUCTION CD DISTRIBUTION API

on:
  push:
    branches:
      - main

jobs:
  distribution_api_production:
    name: Distribution API Production
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout the repository 🎁
        uses: actions/checkout@v2

      - name: Setting up google Cloud SDK 💳
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: core-oss-production
          service_account_key: ${{ secrets.G_CREDENTIALS_PRODUCTION }}
          export_default_credentials: true

      - name: Configure gcloud 👷
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: Build and publish Dockerfile 📦
        run: |
          docker build -f cloud.Dockerfile --tag="europe-west1-docker.pkg.dev/core-oss-production/distribution-api/distribution-api:latest" .
          docker push europe-west1-docker.pkg.dev/core-oss-production/distribution-api/distribution-api:latest

      - name: Trigger deploy 🚀
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow: deployment-production.yml
          repo: PrestaShopCorp/terraform-core-oss-distribution-api
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: 'refs/heads/main'
