name: INTEGRATION CD DISTRIBUTION API

on:
  push:
    branches:
      - deployment

jobs:
  distribution_api_integration:
    name: Distribution API Integration
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout the repository 🎁
        uses: actions/checkout@v2

      - name: Setting up PHP ⚙️
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, intl, gd, xml, dom, json, fileinfo, curl, zip, iconv, simplexml

      - name: Installing Dependencies 🧩
        run: composer install --ansi --prefer-dist --no-interaction --no-progress

      - name: Authenticating to google 🔐
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.INTEGRATION_GOOGLE_APPLICATION_CREDENTIALS }}'
          project_id: ${{ secrets.INTEGRATION_GOOGLE_PROJECT }}

      - name: Setting up google Cloud SDK 🏷️
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.INTEGRATION_GOOGLE_PROJECT }}
          credentials_json: ${{ secrets.INTEGRATION_GOOGLE_APPLICATION_CREDENTIALS }}
          export_default_credentials: true

      - name: Setting up github token... 🧨
        
        run: |
          mv config/parameters.yaml.dist config/parameters.yaml 
          sed -i 's/github_token.*/github_token\:\ ${token}/' config/parameters.yaml 
        env:
          token: ${{secrets.TOKEN}}

